version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: cd test; chmod +x ess_test.py; ./ess_test.py test
          name: Test

workflows:
  main:
    jobs:
      - test

