version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - attach_workspace:
              - dtomci-pygame/test
      - run:
          command: ./ess_test.py test
          name: Test

workflows:
  main:
    jobs:
      - test

