version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - run:
          command: cd ..
          name: Test
      -run :
        command: ls

workflows:
  main:
    jobs:
      - test

