version: 2.1

orbs:
  python: circleci/python@0.2.1

attach_workspace: dtomci-pygame/test

jobs:
  test:
    executor: python/default
    steps:
      - persist_to_workspace: dtomci-pygame/test
      - run:
          command: pwd
          name: Test

workflows:
  main:
    jobs:
      - test

