version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  install:
    steps:
      - run:
          python3 -m pip install -U pygame --user
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: cd test; chmod +x ess_test.py; python ess_test.py test
          name: Test

workflows:
  main:
    jobs:
      - install
      - test

