version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    working_directory: ~/dtomci-pygame/test
    executor: python/default
    steps:
      - run:
          command: pwd
          name: Test

workflows:
  main:
    jobs:
      - test

